/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * walt.id wallet
 * Interact with the walt.id wallet. Version is reported to be 0.20.1 and this service instance was started 2026-06-02T06:38:11Z.<br/>Questions about anything here? Visit <a href='https://walt.id/community'>support</a>.<br/><br/>Any HTTP status code of 200 - 299 indicates request success, 400 - 499 client error / invalid request, 500+ internal server processing exception.
 * OpenAPI spec version: 0.20.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export type IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformationFeatures = {[key: string]: string};

export interface IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformation {
  features: IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformationFeatures;
  total: number;
}

export interface IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformations {
  enabled: IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformation;
  disabled: IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformation;
  defaultedDisabled: IdWaltCommonsWebModulesFeatureFlagInformationModuleFeatureFlagInformation;
}

export interface IdWaltWebwalletDbModelsAccount {
  tenant: string;
  id: string;
  name?: string;
  email?: string;
  createdOn: string;
}

export interface Address {
  name?: string;
  address: string;
  ecosystem: string;
  type?: string;
}

export interface Email {
  name?: string;
  email: string;
  password: string;
  type?: string;
}

export interface Keycloak {
  name?: string;
  email?: string;
  username?: string;
  password?: string;
  token?: string;
  type?: string;
}

export interface Oidc {
  name?: string;
  token: string;
  type?: string;
}

export interface OidcUniqueSubject {
  name?: string;
  token: string;
  type?: string;
}

export interface X5c {
  name?: string;
  token: string;
  type?: string;
}

export type IdWaltWebwalletWebModelAccountRequest = Address | Email | Keycloak | Oidc | OidcUniqueSubject | X5c;

export interface IdWaltWebwalletWebControllersAuthLoginResponseData {
  id: string;
  token: string;
  username?: string;
  address?: string;
  keycloakUserId?: string;
}

export interface IdWaltWebwalletWebModelKeycloakLogoutRequest {
  keycloakUserId?: string;
  token?: string;
}

export interface IdWaltWebwalletDbModelsAccountWalletListingWalletListing {
  id: string;
  name: string;
  createdOn: string;
  addedOn: string;
  permission: IdWaltWebwalletDbModelsAccountWalletPermissions;
}

export type IdWaltWebwalletDbModelsAccountWalletPermissions = typeof IdWaltWebwalletDbModelsAccountWalletPermissions[keyof typeof IdWaltWebwalletDbModelsAccountWalletPermissions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdWaltWebwalletDbModelsAccountWalletPermissions = {
  ADMINISTRATE: 'ADMINISTRATE',
  USE: 'USE',
  READ_ONLY: 'READ_ONLY',
} as const;

export interface IdWaltWebwalletDbModelsAccountWalletListing {
  account: string;
  wallets: IdWaltWebwalletDbModelsAccountWalletListingWalletListing[];
}

export type IdWaltCryptoKeysKeyType = typeof IdWaltCryptoKeysKeyType[keyof typeof IdWaltCryptoKeysKeyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdWaltCryptoKeysKeyType = {
  Ed25519: 'Ed25519',
  secp256k1: 'secp256k1',
  secp256r1: 'secp256r1',
  secp384r1: 'secp384r1',
  secp521r1: 'secp521r1',
  RSA: 'RSA',
  RSA3072: 'RSA3072',
  RSA4096: 'RSA4096',
} as const;

export interface KotlinxSerializationJsonJsonObject { [key: string]: unknown }

export interface IdWaltCryptoKeysKeyGenerationRequest {
  backend: string;
  keyType: IdWaltCryptoKeysKeyType;
  name?: string;
  config?: KotlinxSerializationJsonJsonObject;
}

export interface KotlinxSerializationJsonJsonElement { [key: string]: unknown }

export interface IdWaltWebwalletDbModelsWalletDid {
  did: string;
  alias: string;
  document: string;
  keyId: string;
  default: boolean;
  createdOn: string;
}

export interface IdWaltWebwalletWebModelDidImportRequest {
  did: string;
  key?: KotlinxSerializationJsonJsonElement;
  alias?: string;
}

export interface IdWaltWebwalletDbModelsWalletCredential {
  addedOn: string;
  deletedOn?: string;
  disclosures?: string;
  document: string;
  format: IdWaltOid4vcDataCredentialFormat;
  id: string;
  manifest?: string;
  parsedDocument?: KotlinxSerializationJsonJsonObject;
  parsedManifest?: KotlinxSerializationJsonJsonObject;
  pending: boolean;
  wallet: string;
}

export type IdWaltOid4vcDataCredentialFormat = typeof IdWaltOid4vcDataCredentialFormat[keyof typeof IdWaltOid4vcDataCredentialFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdWaltOid4vcDataCredentialFormat = {
  jwt_vc_json: 'jwt_vc_json',
  jwt_vc_json_ld: 'jwt_vc_json_ld',
  ldp_vc: 'ldp_vc',
  sd_jwt_dc: 'sd_jwt_dc',
  sd_jwt_vc: 'sd_jwt_vc',
  mso_mdoc: 'mso_mdoc',
  jwt_vp_json: 'jwt_vp_json',
  jwt_vp_json_ld: 'jwt_vp_json_ld',
  ldp_vp: 'ldp_vp',
  jwt_vc: 'jwt_vc',
  jwt_vp: 'jwt_vp',
} as const;

export interface IdWaltWebwalletWebModelCredentialImportRequest {
  jwt: string;
  associated_did: string;
}

export interface IdWaltWebwalletWebParameterNoteRequestParameter {
  note: string;
}

export interface IdWaltWebwalletUsecaseCredentialCredentialStatusResult {
  type: string;
  result: boolean;
  message: string;
}

export type IdWaltOid4vcDataDifInputDescriptorFormat = {[key: string]: IdWaltOid4vcDataDifVCFormatDefinition};

export interface IdWaltOid4vcDataDifInputDescriptor {
  id: string;
  name?: string;
  purpose?: string;
  format?: IdWaltOid4vcDataDifInputDescriptorFormat;
  constraints?: IdWaltOid4vcDataDifInputDescriptorConstraints;
  schema?: IdWaltOid4vcDataDifInputDescriptorSchema[];
  group?: string[];
  [key: string]: unknown;
}

export interface IdWaltOid4vcDataDifVCFormatDefinition {
  alg?: string[];
  proof_type?: string[];
  [key: string]: unknown;
}

export interface IdWaltOid4vcDataDifInputDescriptorConstraints {
  fields?: IdWaltOid4vcDataDifInputDescriptorField[];
  limit_disclosure?: IdWaltOid4vcDataDifDisclosureLimitation;
  [key: string]: unknown;
}

export interface IdWaltOid4vcDataDifInputDescriptorField {
  path: string[];
  id?: string;
  purpose?: string;
  name?: string;
  filter?: KotlinxSerializationJsonJsonObject;
  optional?: boolean;
  intent_to_retain?: boolean;
  [key: string]: unknown;
}

export type IdWaltOid4vcDataDifDisclosureLimitation = typeof IdWaltOid4vcDataDifDisclosureLimitation[keyof typeof IdWaltOid4vcDataDifDisclosureLimitation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdWaltOid4vcDataDifDisclosureLimitation = {
  required: 'required',
  preferred: 'preferred',
} as const;

export interface IdWaltOid4vcDataDifInputDescriptorSchema {
  uri: string;
  [key: string]: unknown;
}

export interface IdWaltOid4vcDataDifSubmissionRequirement {
  rule: IdWaltOid4vcDataDifSubmissionRequirementRule;
  from?: string;
  from_nested?: IdWaltOid4vcDataDifSubmissionRequirement[];
  name?: string;
  purpose?: string;
  count?: number;
  min?: number;
  max?: number;
  [key: string]: unknown;
}

export type IdWaltOid4vcDataDifSubmissionRequirementRule = typeof IdWaltOid4vcDataDifSubmissionRequirementRule[keyof typeof IdWaltOid4vcDataDifSubmissionRequirementRule];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdWaltOid4vcDataDifSubmissionRequirementRule = {
  pick: 'pick',
  all: 'all',
} as const;

export type IdWaltOid4vcDataDifPresentationDefinitionFormat = {[key: string]: IdWaltOid4vcDataDifVCFormatDefinition};

export interface IdWaltOid4vcDataDifPresentationDefinition {
  id: string;
  input_descriptors: IdWaltOid4vcDataDifInputDescriptor[];
  name?: string;
  purpose?: string;
  format?: IdWaltOid4vcDataDifPresentationDefinitionFormat;
  submission_requirements?: IdWaltOid4vcDataDifSubmissionRequirement[];
  [key: string]: unknown;
}

export interface IdWaltWebwalletUsecaseExchangeFilterData {
  credential: string;
  filters: IdWaltWebwalletUsecaseExchangeTypeFilter[];
}

export interface IdWaltWebwalletUsecaseExchangeTypeFilter {
  path: string[];
  type?: string;
  pattern: string;
}

export type IdWaltWebwalletWebControllersExchangeUsePresentationRequestDisclosures = {[key: string]: string[]};

export interface IdWaltWebwalletWebControllersExchangeUsePresentationRequest {
  did?: string;
  presentationRequest: string;
  selectedCredentials: string[];
  disclosures?: IdWaltWebwalletWebControllersExchangeUsePresentationRequestDisclosures;
  note?: string;
}

export interface IdWaltOid4vcDataCredentialOffer { [key: string]: unknown }

export interface IdWaltSdjwtMetadataTypeSdJwtVcTypeMetadataDraft04 {
  vct?: string;
  name?: string;
  description?: string;
  extends?: string;
  'extends#integrity'?: string;
  schema?: KotlinxSerializationJsonJsonObject;
  schema_uri?: string;
  'schema_uri#integrity'?: string;
  [key: string]: unknown;
}

export interface IdWaltOid4vcDataOpenIDProviderMetadata { [key: string]: unknown }

export interface IdWaltWebwalletDbModelsWalletOperationHistory {
  tenant: string;
  id?: string;
  account: string;
  wallet: string;
  timestamp: string;
  operation: string;
  data: KotlinxSerializationJsonJsonObject;
}

export interface IdWaltWebwalletServiceIssuersIssuerDataTransferObject {
  wallet: string;
  did: string;
  description?: string;
  uiEndpoint: string;
  configurationEndpoint: string;
  authorized: boolean;
}

export interface IdWaltWebwalletWebControllersIssuerParameter {
  name: string;
  description?: string;
  uiEndpoint: string;
  configurationEndpoint: string;
}

export interface IdWaltWebwalletServiceIssuersCredentialDataTransferObject {
  id: string;
  format: string;
  types: string[];
}

export interface IdWaltWebwalletDbModelsWalletCategoryData {
  name: string;
}

export interface IdWaltWebwalletServiceSettingsWalletSetting {
  settings: KotlinxSerializationJsonJsonObject;
}

export type CreateDidKeyParams = {
/**
 * Optionally override a key ID to use (otherwise will generate a new one if not present)
 */
keyId?: string;
/**
 * Optionally set key alias (otherwise will use hash of key if not present)
 */
alias?: string;
/**
 * Optionally set JWK JCS Pub format (for e.g. EBSI)
 */
useJwkJcsPub?: boolean;
};

/**
 * @summary Register with [email + password] or [wallet address + ecosystem]
 */
export type registerUserResponse201 = {
  data: void
  status: 201
}

export type registerUserResponse400 = {
  data: void
  status: 400
}
    
export type registerUserResponseComposite = registerUserResponse201 | registerUserResponse400;
    
export type registerUserResponse = registerUserResponseComposite & {
  headers: Headers;
}

export const getRegisterUserUrl = () => {


  

  return `/wallet-api/auth/register`
}

export const registerUser = async (idWaltWebwalletWebModelAccountRequest: IdWaltWebwalletWebModelAccountRequest, options?: RequestInit): Promise<registerUserResponse> => {
  
  const res = await fetch(getRegisterUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      idWaltWebwalletWebModelAccountRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: registerUserResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as registerUserResponse
}




export const getRegisterUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: IdWaltWebwalletWebModelAccountRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: IdWaltWebwalletWebModelAccountRequest}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: IdWaltWebwalletWebModelAccountRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = IdWaltWebwalletWebModelAccountRequest
    export type RegisterUserMutationError = void

    /**
 * @summary Register with [email + password] or [wallet address + ecosystem]
 */
export const useRegisterUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: IdWaltWebwalletWebModelAccountRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: IdWaltWebwalletWebModelAccountRequest},
        TContext
      > => {

      const mutationOptions = getRegisterUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Login with [email + password] or [wallet address + ecosystem] or [oidc session]
 */
export type loginUserResponse200 = {
  data: IdWaltWebwalletWebControllersAuthLoginResponseData
  status: 200
}

export type loginUserResponse400 = {
  data: void
  status: 400
}
    
export type loginUserResponseComposite = loginUserResponse200 | loginUserResponse400;
    
export type loginUserResponse = loginUserResponseComposite & {
  headers: Headers;
}

export const getLoginUserUrl = () => {


  

  return `/wallet-api/auth/login`
}

export const loginUser = async (idWaltWebwalletWebModelAccountRequest: IdWaltWebwalletWebModelAccountRequest, options?: RequestInit): Promise<loginUserResponse> => {
  
  const res = await fetch(getLoginUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      idWaltWebwalletWebModelAccountRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: loginUserResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as loginUserResponse
}




export const getLoginUserMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: IdWaltWebwalletWebModelAccountRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: IdWaltWebwalletWebModelAccountRequest}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: IdWaltWebwalletWebModelAccountRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = IdWaltWebwalletWebModelAccountRequest
    export type LoginUserMutationError = void

    /**
 * @summary Login with [email + password] or [wallet address + ecosystem] or [oidc session]
 */
export const useLoginUser = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: IdWaltWebwalletWebModelAccountRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: IdWaltWebwalletWebModelAccountRequest},
        TContext
      > => {

      const mutationOptions = getLoginUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Logout (delete session)
 */
export type logoutUserResponse200 = {
  data: void
  status: 200
}
    
export type logoutUserResponseComposite = logoutUserResponse200;
    
export type logoutUserResponse = logoutUserResponseComposite & {
  headers: Headers;
}

export const getLogoutUserUrl = () => {


  

  return `/wallet-api/auth/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  const res = await fetch(getLogoutUserUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: logoutUserResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as logoutUserResponse
}




export const getLogoutUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, void> = () => {
          

          return  logoutUser(fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
    
    export type LogoutUserMutationError = unknown

    /**
 * @summary Logout (delete session)
 */
export const useLogoutUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Get wallets associated with account
 */
export type getWalletsResponse200 = {
  data: IdWaltWebwalletDbModelsAccountWalletListing
  status: 200
}

export type getWalletsResponse401 = {
  data: void
  status: 401
}
    
export type getWalletsResponseComposite = getWalletsResponse200 | getWalletsResponse401;
    
export type getWalletsResponse = getWalletsResponseComposite & {
  headers: Headers;
}

export const getGetWalletsUrl = () => {


  

  return `/wallet-api/wallet/accounts/wallets`
}

export const getWallets = async ( options?: RequestInit): Promise<getWalletsResponse> => {
  
  const res = await fetch(getGetWalletsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getWalletsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getWalletsResponse
}



export const getGetWalletsQueryKey = () => {
    return [`/wallet-api/wallet/accounts/wallets`] as const;
    }

    
export const getGetWalletsQueryOptions = <TData = Awaited<ReturnType<typeof getWallets>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWallets>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWallets>>> = ({ signal }) => getWallets({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWallets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWalletsQueryResult = NonNullable<Awaited<ReturnType<typeof getWallets>>>
export type GetWalletsQueryError = void


export function useGetWallets<TData = Awaited<ReturnType<typeof getWallets>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWallets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWallets>>,
          TError,
          Awaited<ReturnType<typeof getWallets>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWallets<TData = Awaited<ReturnType<typeof getWallets>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWallets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWallets>>,
          TError,
          Awaited<ReturnType<typeof getWallets>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWallets<TData = Awaited<ReturnType<typeof getWallets>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWallets>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get wallets associated with account
 */

export function useGetWallets<TData = Awaited<ReturnType<typeof getWallets>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWallets>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWalletsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Generate new key
 */
export type generateKeyResponse201 = {
  data: string
  status: 201
}

export type generateKeyResponse401 = {
  data: void
  status: 401
}
    
export type generateKeyResponseComposite = generateKeyResponse201 | generateKeyResponse401;
    
export type generateKeyResponse = generateKeyResponseComposite & {
  headers: Headers;
}

export const getGenerateKeyUrl = (wallet: string,) => {


  

  return `/wallet-api/wallet/${wallet}/keys/generate`
}

export const generateKey = async (wallet: string,
    idWaltCryptoKeysKeyGenerationRequest: IdWaltCryptoKeysKeyGenerationRequest, options?: RequestInit): Promise<generateKeyResponse> => {
  
  const res = await fetch(getGenerateKeyUrl(wallet),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      idWaltCryptoKeysKeyGenerationRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: generateKeyResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as generateKeyResponse
}




export const getGenerateKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateKey>>, TError,{wallet: string;data: IdWaltCryptoKeysKeyGenerationRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateKey>>, TError,{wallet: string;data: IdWaltCryptoKeysKeyGenerationRequest}, TContext> => {

const mutationKey = ['generateKey'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateKey>>, {wallet: string;data: IdWaltCryptoKeysKeyGenerationRequest}> = (props) => {
          const {wallet,data} = props ?? {};

          return  generateKey(wallet,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateKeyMutationResult = NonNullable<Awaited<ReturnType<typeof generateKey>>>
    export type GenerateKeyMutationBody = IdWaltCryptoKeysKeyGenerationRequest
    export type GenerateKeyMutationError = void

    /**
 * @summary Generate new key
 */
export const useGenerateKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateKey>>, TError,{wallet: string;data: IdWaltCryptoKeysKeyGenerationRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateKey>>,
        TError,
        {wallet: string;data: IdWaltCryptoKeysKeyGenerationRequest},
        TContext
      > => {

      const mutationOptions = getGenerateKeyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Create a did:key
 */
export type createDidKeyResponse200 = {
  data: void
  status: 200
}

export type createDidKeyResponse400 = {
  data: void
  status: 400
}
    
export type createDidKeyResponseComposite = createDidKeyResponse200 | createDidKeyResponse400;
    
export type createDidKeyResponse = createDidKeyResponseComposite & {
  headers: Headers;
}

export const getCreateDidKeyUrl = (wallet: string,
    params?: CreateDidKeyParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/wallet-api/wallet/${wallet}/dids/create/key?${stringifiedParams}` : `/wallet-api/wallet/${wallet}/dids/create/key`
}

export const createDidKey = async (wallet: string,
    params?: CreateDidKeyParams, options?: RequestInit): Promise<createDidKeyResponse> => {
  
  const res = await fetch(getCreateDidKeyUrl(wallet,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: createDidKeyResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as createDidKeyResponse
}




export const getCreateDidKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDidKey>>, TError,{wallet: string;params?: CreateDidKeyParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createDidKey>>, TError,{wallet: string;params?: CreateDidKeyParams}, TContext> => {

const mutationKey = ['createDidKey'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDidKey>>, {wallet: string;params?: CreateDidKeyParams}> = (props) => {
          const {wallet,params} = props ?? {};

          return  createDidKey(wallet,params,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDidKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createDidKey>>>
    
    export type CreateDidKeyMutationError = void

    /**
 * @summary Create a did:key
 */
export const useCreateDidKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDidKey>>, TError,{wallet: string;params?: CreateDidKeyParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDidKey>>,
        TError,
        {wallet: string;params?: CreateDidKeyParams},
        TContext
      > => {

      const mutationOptions = getCreateDidKeyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * @summary Import a signed VC JWT into the wallet
 */
export type importCredentialResponse201 = {
  data: IdWaltWebwalletDbModelsWalletCredential
  status: 201
}

export type importCredentialResponse400 = {
  data: void
  status: 400
}
    
export type importCredentialResponseComposite = importCredentialResponse201 | importCredentialResponse400;
    
export type importCredentialResponse = importCredentialResponseComposite & {
  headers: Headers;
}

export const getImportCredentialUrl = (wallet: string,) => {


  

  return `/wallet-api/wallet/${wallet}/credentials/import`
}

export const importCredential = async (wallet: string,
    idWaltWebwalletWebModelCredentialImportRequest: IdWaltWebwalletWebModelCredentialImportRequest, options?: RequestInit): Promise<importCredentialResponse> => {
  
  const res = await fetch(getImportCredentialUrl(wallet),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      idWaltWebwalletWebModelCredentialImportRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: importCredentialResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as importCredentialResponse
}




export const getImportCredentialMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importCredential>>, TError,{wallet: string;data: IdWaltWebwalletWebModelCredentialImportRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof importCredential>>, TError,{wallet: string;data: IdWaltWebwalletWebModelCredentialImportRequest}, TContext> => {

const mutationKey = ['importCredential'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importCredential>>, {wallet: string;data: IdWaltWebwalletWebModelCredentialImportRequest}> = (props) => {
          const {wallet,data} = props ?? {};

          return  importCredential(wallet,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportCredentialMutationResult = NonNullable<Awaited<ReturnType<typeof importCredential>>>
    export type ImportCredentialMutationBody = IdWaltWebwalletWebModelCredentialImportRequest
    export type ImportCredentialMutationError = void

    /**
 * @summary Import a signed VC JWT into the wallet
 */
export const useImportCredential = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importCredential>>, TError,{wallet: string;data: IdWaltWebwalletWebModelCredentialImportRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importCredential>>,
        TError,
        {wallet: string;data: IdWaltWebwalletWebModelCredentialImportRequest},
        TContext
      > => {

      const mutationOptions = getImportCredentialMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
